/*
 * Hotelspro Api Client
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hotelspro_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import hotelspro_client.model.BookResponseConfirmationNumbers;
import hotelspro_client.model.BookResponseHotelPaymentInfo;
import hotelspro_client.model.Policy;
import hotelspro_client.model.Room;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BookResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T16:34:00.424+03:00")
public class BookResponse {
  @SerializedName("code")
  private String code = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("checkin")
  private String checkin = null;

  @SerializedName("checkout")
  private String checkout = null;

  @SerializedName("hotel_code")
  private String hotelCode = null;

  @SerializedName("destination_code")
  private String destinationCode = null;

  @SerializedName("client_nationality")
  private String clientNationality = null;

  @SerializedName("pay_at_hotel")
  private Boolean payAtHotel = null;

  /**
   * Gets or Sets currency
   */
  @JsonAdapter(CurrencyEnum.Adapter.class)
  public enum CurrencyEnum {
    USD("USD"),
    
    EUR("EUR"),
    
    GBP("GBP"),
    
    TRY("TRY"),
    
    AED("AED");

    private String value;

    CurrencyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CurrencyEnum fromValue(String text) {
      for (CurrencyEnum b : CurrencyEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<CurrencyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CurrencyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CurrencyEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CurrencyEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("currency")
  private CurrencyEnum currency = null;

  @SerializedName("mealtype_code")
  private String mealtypeCode = null;

  @SerializedName("nonrefundable")
  private String nonrefundable = null;

  @SerializedName("view")
  private Boolean view = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("policies")
  private List<Policy> policies = new ArrayList<Policy>();

  @SerializedName("rooms")
  private List<Room> rooms = new ArrayList<Room>();

  @SerializedName("status")
  private String status = null;

  @SerializedName("confirmation_numbers")
  private List<BookResponseConfirmationNumbers> confirmationNumbers = new ArrayList<BookResponseConfirmationNumbers>();

  @SerializedName("hotel_payment_info")
  private List<BookResponseHotelPaymentInfo> hotelPaymentInfo = new ArrayList<BookResponseHotelPaymentInfo>();

  @SerializedName("minimum_selling_price")
  private String minimumSellingPrice = null;

  @SerializedName("special_request")
  private String specialRequest = null;

  public BookResponse code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public BookResponse createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public BookResponse checkin(String checkin) {
    this.checkin = checkin;
    return this;
  }

   /**
   * Get checkin
   * @return checkin
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCheckin() {
    return checkin;
  }

  public void setCheckin(String checkin) {
    this.checkin = checkin;
  }

  public BookResponse checkout(String checkout) {
    this.checkout = checkout;
    return this;
  }

   /**
   * Get checkout
   * @return checkout
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCheckout() {
    return checkout;
  }

  public void setCheckout(String checkout) {
    this.checkout = checkout;
  }

  public BookResponse hotelCode(String hotelCode) {
    this.hotelCode = hotelCode;
    return this;
  }

   /**
   * Get hotelCode
   * @return hotelCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getHotelCode() {
    return hotelCode;
  }

  public void setHotelCode(String hotelCode) {
    this.hotelCode = hotelCode;
  }

  public BookResponse destinationCode(String destinationCode) {
    this.destinationCode = destinationCode;
    return this;
  }

   /**
   * Get destinationCode
   * @return destinationCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDestinationCode() {
    return destinationCode;
  }

  public void setDestinationCode(String destinationCode) {
    this.destinationCode = destinationCode;
  }

  public BookResponse clientNationality(String clientNationality) {
    this.clientNationality = clientNationality;
    return this;
  }

   /**
   * Get clientNationality
   * @return clientNationality
  **/
  @ApiModelProperty(required = true, value = "")
  public String getClientNationality() {
    return clientNationality;
  }

  public void setClientNationality(String clientNationality) {
    this.clientNationality = clientNationality;
  }

  public BookResponse payAtHotel(Boolean payAtHotel) {
    this.payAtHotel = payAtHotel;
    return this;
  }

   /**
   * Get payAtHotel
   * @return payAtHotel
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getPayAtHotel() {
    return payAtHotel;
  }

  public void setPayAtHotel(Boolean payAtHotel) {
    this.payAtHotel = payAtHotel;
  }

  public BookResponse currency(CurrencyEnum currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(required = true, value = "")
  public CurrencyEnum getCurrency() {
    return currency;
  }

  public void setCurrency(CurrencyEnum currency) {
    this.currency = currency;
  }

  public BookResponse mealtypeCode(String mealtypeCode) {
    this.mealtypeCode = mealtypeCode;
    return this;
  }

   /**
   * Get mealtypeCode
   * @return mealtypeCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMealtypeCode() {
    return mealtypeCode;
  }

  public void setMealtypeCode(String mealtypeCode) {
    this.mealtypeCode = mealtypeCode;
  }

  public BookResponse nonrefundable(String nonrefundable) {
    this.nonrefundable = nonrefundable;
    return this;
  }

   /**
   * Get nonrefundable
   * @return nonrefundable
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNonrefundable() {
    return nonrefundable;
  }

  public void setNonrefundable(String nonrefundable) {
    this.nonrefundable = nonrefundable;
  }

  public BookResponse view(Boolean view) {
    this.view = view;
    return this;
  }

   /**
   * Get view
   * @return view
  **/
  @ApiModelProperty(value = "")
  public Boolean getView() {
    return view;
  }

  public void setView(Boolean view) {
    this.view = view;
  }

  public BookResponse price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public BookResponse policies(List<Policy> policies) {
    this.policies = policies;
    return this;
  }

  public BookResponse addPoliciesItem(Policy policiesItem) {
    this.policies.add(policiesItem);
    return this;
  }

   /**
   * Get policies
   * @return policies
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Policy> getPolicies() {
    return policies;
  }

  public void setPolicies(List<Policy> policies) {
    this.policies = policies;
  }

  public BookResponse rooms(List<Room> rooms) {
    this.rooms = rooms;
    return this;
  }

  public BookResponse addRoomsItem(Room roomsItem) {
    this.rooms.add(roomsItem);
    return this;
  }

   /**
   * Get rooms
   * @return rooms
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Room> getRooms() {
    return rooms;
  }

  public void setRooms(List<Room> rooms) {
    this.rooms = rooms;
  }

  public BookResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public BookResponse confirmationNumbers(List<BookResponseConfirmationNumbers> confirmationNumbers) {
    this.confirmationNumbers = confirmationNumbers;
    return this;
  }

  public BookResponse addConfirmationNumbersItem(BookResponseConfirmationNumbers confirmationNumbersItem) {
    this.confirmationNumbers.add(confirmationNumbersItem);
    return this;
  }

   /**
   * Get confirmationNumbers
   * @return confirmationNumbers
  **/
  @ApiModelProperty(required = true, value = "")
  public List<BookResponseConfirmationNumbers> getConfirmationNumbers() {
    return confirmationNumbers;
  }

  public void setConfirmationNumbers(List<BookResponseConfirmationNumbers> confirmationNumbers) {
    this.confirmationNumbers = confirmationNumbers;
  }

  public BookResponse hotelPaymentInfo(List<BookResponseHotelPaymentInfo> hotelPaymentInfo) {
    this.hotelPaymentInfo = hotelPaymentInfo;
    return this;
  }

  public BookResponse addHotelPaymentInfoItem(BookResponseHotelPaymentInfo hotelPaymentInfoItem) {
    this.hotelPaymentInfo.add(hotelPaymentInfoItem);
    return this;
  }

   /**
   * Get hotelPaymentInfo
   * @return hotelPaymentInfo
  **/
  @ApiModelProperty(required = true, value = "")
  public List<BookResponseHotelPaymentInfo> getHotelPaymentInfo() {
    return hotelPaymentInfo;
  }

  public void setHotelPaymentInfo(List<BookResponseHotelPaymentInfo> hotelPaymentInfo) {
    this.hotelPaymentInfo = hotelPaymentInfo;
  }

  public BookResponse minimumSellingPrice(String minimumSellingPrice) {
    this.minimumSellingPrice = minimumSellingPrice;
    return this;
  }

   /**
   * Get minimumSellingPrice
   * @return minimumSellingPrice
  **/
  @ApiModelProperty(value = "")
  public String getMinimumSellingPrice() {
    return minimumSellingPrice;
  }

  public void setMinimumSellingPrice(String minimumSellingPrice) {
    this.minimumSellingPrice = minimumSellingPrice;
  }

  public BookResponse specialRequest(String specialRequest) {
    this.specialRequest = specialRequest;
    return this;
  }

   /**
   * Get specialRequest
   * @return specialRequest
  **/
  @ApiModelProperty(value = "")
  public String getSpecialRequest() {
    return specialRequest;
  }

  public void setSpecialRequest(String specialRequest) {
    this.specialRequest = specialRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookResponse bookResponse = (BookResponse) o;
    return Objects.equals(this.code, bookResponse.code) &&
        Objects.equals(this.createdAt, bookResponse.createdAt) &&
        Objects.equals(this.checkin, bookResponse.checkin) &&
        Objects.equals(this.checkout, bookResponse.checkout) &&
        Objects.equals(this.hotelCode, bookResponse.hotelCode) &&
        Objects.equals(this.destinationCode, bookResponse.destinationCode) &&
        Objects.equals(this.clientNationality, bookResponse.clientNationality) &&
        Objects.equals(this.payAtHotel, bookResponse.payAtHotel) &&
        Objects.equals(this.currency, bookResponse.currency) &&
        Objects.equals(this.mealtypeCode, bookResponse.mealtypeCode) &&
        Objects.equals(this.nonrefundable, bookResponse.nonrefundable) &&
        Objects.equals(this.view, bookResponse.view) &&
        Objects.equals(this.price, bookResponse.price) &&
        Objects.equals(this.policies, bookResponse.policies) &&
        Objects.equals(this.rooms, bookResponse.rooms) &&
        Objects.equals(this.status, bookResponse.status) &&
        Objects.equals(this.confirmationNumbers, bookResponse.confirmationNumbers) &&
        Objects.equals(this.hotelPaymentInfo, bookResponse.hotelPaymentInfo) &&
        Objects.equals(this.minimumSellingPrice, bookResponse.minimumSellingPrice) &&
        Objects.equals(this.specialRequest, bookResponse.specialRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, createdAt, checkin, checkout, hotelCode, destinationCode, clientNationality, payAtHotel, currency, mealtypeCode, nonrefundable, view, price, policies, rooms, status, confirmationNumbers, hotelPaymentInfo, minimumSellingPrice, specialRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookResponse {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    checkin: ").append(toIndentedString(checkin)).append("\n");
    sb.append("    checkout: ").append(toIndentedString(checkout)).append("\n");
    sb.append("    hotelCode: ").append(toIndentedString(hotelCode)).append("\n");
    sb.append("    destinationCode: ").append(toIndentedString(destinationCode)).append("\n");
    sb.append("    clientNationality: ").append(toIndentedString(clientNationality)).append("\n");
    sb.append("    payAtHotel: ").append(toIndentedString(payAtHotel)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    mealtypeCode: ").append(toIndentedString(mealtypeCode)).append("\n");
    sb.append("    nonrefundable: ").append(toIndentedString(nonrefundable)).append("\n");
    sb.append("    view: ").append(toIndentedString(view)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
    sb.append("    rooms: ").append(toIndentedString(rooms)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    confirmationNumbers: ").append(toIndentedString(confirmationNumbers)).append("\n");
    sb.append("    hotelPaymentInfo: ").append(toIndentedString(hotelPaymentInfo)).append("\n");
    sb.append("    minimumSellingPrice: ").append(toIndentedString(minimumSellingPrice)).append("\n");
    sb.append("    specialRequest: ").append(toIndentedString(specialRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

