/*
 * Hotelspro Api Client
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hotelspro_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import hotelspro_client.model.Product;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * HotelAvailabilityResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T16:34:00.424+03:00")
public class HotelAvailabilityResponse {
  @SerializedName("count")
  private Integer count = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("results")
  private List<Product> results = new ArrayList<Product>();

  public HotelAvailabilityResponse count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * number of returned hotel
   * @return count
  **/
  @ApiModelProperty(required = true, value = "number of returned hotel")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public HotelAvailabilityResponse code(String code) {
    this.code = code;
    return this;
  }

   /**
   * search code
   * @return code
  **/
  @ApiModelProperty(required = true, value = "search code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public HotelAvailabilityResponse results(List<Product> results) {
    this.results = results;
    return this;
  }

  public HotelAvailabilityResponse addResultsItem(Product resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Product> getResults() {
    return results;
  }

  public void setResults(List<Product> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelAvailabilityResponse hotelAvailabilityResponse = (HotelAvailabilityResponse) o;
    return Objects.equals(this.count, hotelAvailabilityResponse.count) &&
        Objects.equals(this.code, hotelAvailabilityResponse.code) &&
        Objects.equals(this.results, hotelAvailabilityResponse.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, code, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelAvailabilityResponse {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

