/*
 * Hotelspro Api Client
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hotelspro_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Pax
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T16:34:00.424+03:00")
public class Pax {
  @SerializedName("adult_quantity")
  private Integer adultQuantity = null;

  @SerializedName("children_ages")
  private List<Integer> childrenAges = null;

  public Pax adultQuantity(Integer adultQuantity) {
    this.adultQuantity = adultQuantity;
    return this;
  }

   /**
   * Get adultQuantity
   * @return adultQuantity
  **/
  @ApiModelProperty(value = "")
  public Integer getAdultQuantity() {
    return adultQuantity;
  }

  public void setAdultQuantity(Integer adultQuantity) {
    this.adultQuantity = adultQuantity;
  }

  public Pax childrenAges(List<Integer> childrenAges) {
    this.childrenAges = childrenAges;
    return this;
  }

  public Pax addChildrenAgesItem(Integer childrenAgesItem) {
    if (this.childrenAges == null) {
      this.childrenAges = new ArrayList<Integer>();
    }
    this.childrenAges.add(childrenAgesItem);
    return this;
  }

   /**
   * Get childrenAges
   * @return childrenAges
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getChildrenAges() {
    return childrenAges;
  }

  public void setChildrenAges(List<Integer> childrenAges) {
    this.childrenAges = childrenAges;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pax pax = (Pax) o;
    return Objects.equals(this.adultQuantity, pax.adultQuantity) &&
        Objects.equals(this.childrenAges, pax.childrenAges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adultQuantity, childrenAges);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pax {\n");
    
    sb.append("    adultQuantity: ").append(toIndentedString(adultQuantity)).append("\n");
    sb.append("    childrenAges: ").append(toIndentedString(childrenAges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

