/*
 * Hotelspro Api Client
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hotelspro_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Policy
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T16:34:00.424+03:00")
public class Policy {
  @SerializedName("ratio")
  private String ratio = null;

  @SerializedName("days_remaining")
  private Integer daysRemaining = null;

  public Policy ratio(String ratio) {
    this.ratio = ratio;
    return this;
  }

   /**
   * Get ratio
   * @return ratio
  **/
  @ApiModelProperty(value = "")
  public String getRatio() {
    return ratio;
  }

  public void setRatio(String ratio) {
    this.ratio = ratio;
  }

  public Policy daysRemaining(Integer daysRemaining) {
    this.daysRemaining = daysRemaining;
    return this;
  }

   /**
   * Get daysRemaining
   * @return daysRemaining
  **/
  @ApiModelProperty(value = "")
  public Integer getDaysRemaining() {
    return daysRemaining;
  }

  public void setDaysRemaining(Integer daysRemaining) {
    this.daysRemaining = daysRemaining;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Policy policy = (Policy) o;
    return Objects.equals(this.ratio, policy.ratio) &&
        Objects.equals(this.daysRemaining, policy.daysRemaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ratio, daysRemaining);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Policy {\n");
    
    sb.append("    ratio: ").append(toIndentedString(ratio)).append("\n");
    sb.append("    daysRemaining: ").append(toIndentedString(daysRemaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

