/*
 * Hotelspro Api Client
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hotelspro_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import hotelspro_client.model.Pax;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Room
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T16:34:00.424+03:00")
public class Room {
  @SerializedName("pax")
  private Pax pax = null;

  @SerializedName("room_category")
  private String roomCategory = null;

  @SerializedName("room_description")
  private String roomDescription = null;

  @SerializedName("nightly_prices")
  private Object nightlyPrices = null;

  @SerializedName("room_type")
  private String roomType = null;

  public Room pax(Pax pax) {
    this.pax = pax;
    return this;
  }

   /**
   * Get pax
   * @return pax
  **/
  @ApiModelProperty(value = "")
  public Pax getPax() {
    return pax;
  }

  public void setPax(Pax pax) {
    this.pax = pax;
  }

  public Room roomCategory(String roomCategory) {
    this.roomCategory = roomCategory;
    return this;
  }

   /**
   * Get roomCategory
   * @return roomCategory
  **/
  @ApiModelProperty(value = "")
  public String getRoomCategory() {
    return roomCategory;
  }

  public void setRoomCategory(String roomCategory) {
    this.roomCategory = roomCategory;
  }

  public Room roomDescription(String roomDescription) {
    this.roomDescription = roomDescription;
    return this;
  }

   /**
   * Get roomDescription
   * @return roomDescription
  **/
  @ApiModelProperty(value = "")
  public String getRoomDescription() {
    return roomDescription;
  }

  public void setRoomDescription(String roomDescription) {
    this.roomDescription = roomDescription;
  }

  public Room nightlyPrices(Object nightlyPrices) {
    this.nightlyPrices = nightlyPrices;
    return this;
  }

   /**
   * Get nightlyPrices
   * @return nightlyPrices
  **/
  @ApiModelProperty(value = "")
  public Object getNightlyPrices() {
    return nightlyPrices;
  }

  public void setNightlyPrices(Object nightlyPrices) {
    this.nightlyPrices = nightlyPrices;
  }

  public Room roomType(String roomType) {
    this.roomType = roomType;
    return this;
  }

   /**
   * Get roomType
   * @return roomType
  **/
  @ApiModelProperty(value = "")
  public String getRoomType() {
    return roomType;
  }

  public void setRoomType(String roomType) {
    this.roomType = roomType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Room room = (Room) o;
    return Objects.equals(this.pax, room.pax) &&
        Objects.equals(this.roomCategory, room.roomCategory) &&
        Objects.equals(this.roomDescription, room.roomDescription) &&
        Objects.equals(this.nightlyPrices, room.nightlyPrices) &&
        Objects.equals(this.roomType, room.roomType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pax, roomCategory, roomDescription, nightlyPrices, roomType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Room {\n");
    
    sb.append("    pax: ").append(toIndentedString(pax)).append("\n");
    sb.append("    roomCategory: ").append(toIndentedString(roomCategory)).append("\n");
    sb.append("    roomDescription: ").append(toIndentedString(roomDescription)).append("\n");
    sb.append("    nightlyPrices: ").append(toIndentedString(nightlyPrices)).append("\n");
    sb.append("    roomType: ").append(toIndentedString(roomType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

