/*
 * Hotelspro Api Client
 * Hotelspro Api Client
 *
 * OpenAPI spec version: 2.0.0
 * Contact: clientintegration@hotelspro.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hotelspro_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import hotelspro_client.model.Results;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SearchResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T16:34:00.424+03:00")
public class SearchResponse {
  @SerializedName("count")
  private Integer count = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("next_page_code")
  private String nextPageCode = null;

  @SerializedName("max_wait")
  private String maxWait = null;

  @SerializedName("response_time")
  private String responseTime = null;

  @SerializedName("results")
  private List<Results> results = new ArrayList<Results>();

  public SearchResponse count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * number of returned hotel
   * @return count
  **/
  @ApiModelProperty(required = true, value = "number of returned hotel")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public SearchResponse code(String code) {
    this.code = code;
    return this;
  }

   /**
   * search code
   * @return code
  **/
  @ApiModelProperty(required = true, value = "search code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public SearchResponse nextPageCode(String nextPageCode) {
    this.nextPageCode = nextPageCode;
    return this;
  }

   /**
   * next page code
   * @return nextPageCode
  **/
  @ApiModelProperty(value = "next page code")
  public String getNextPageCode() {
    return nextPageCode;
  }

  public void setNextPageCode(String nextPageCode) {
    this.nextPageCode = nextPageCode;
  }

  public SearchResponse maxWait(String maxWait) {
    this.maxWait = maxWait;
    return this;
  }

   /**
   * Get maxWait
   * @return maxWait
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMaxWait() {
    return maxWait;
  }

  public void setMaxWait(String maxWait) {
    this.maxWait = maxWait;
  }

  public SearchResponse responseTime(String responseTime) {
    this.responseTime = responseTime;
    return this;
  }

   /**
   * Get responseTime
   * @return responseTime
  **/
  @ApiModelProperty(required = true, value = "")
  public String getResponseTime() {
    return responseTime;
  }

  public void setResponseTime(String responseTime) {
    this.responseTime = responseTime;
  }

  public SearchResponse results(List<Results> results) {
    this.results = results;
    return this;
  }

  public SearchResponse addResultsItem(Results resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Results> getResults() {
    return results;
  }

  public void setResults(List<Results> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResponse searchResponse = (SearchResponse) o;
    return Objects.equals(this.count, searchResponse.count) &&
        Objects.equals(this.code, searchResponse.code) &&
        Objects.equals(this.nextPageCode, searchResponse.nextPageCode) &&
        Objects.equals(this.maxWait, searchResponse.maxWait) &&
        Objects.equals(this.responseTime, searchResponse.responseTime) &&
        Objects.equals(this.results, searchResponse.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, code, nextPageCode, maxWait, responseTime, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResponse {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    nextPageCode: ").append(toIndentedString(nextPageCode)).append("\n");
    sb.append("    maxWait: ").append(toIndentedString(maxWait)).append("\n");
    sb.append("    responseTime: ").append(toIndentedString(responseTime)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

